spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.redis.host=localhost
spring.redis.port=6379

# Se quiser testar localmente sem Redis, comente a linha acima e use:
# spring.cache.type=simple
